"""api models

Revision ID: 27a6cad86571
Revises: 
Create Date: 2022-08-23 11:33:39.517018

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '27a6cad86571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
                    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
                    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('api_key', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_account_api_key'), 'account', ['api_key'], unique=True)
    op.create_table('bank_list',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('mfo', sa.Integer(), nullable=True),
                    sa.Column('edrpou', sa.Integer(), nullable=True),
                    sa.Column('ipn', sa.BigInteger(), nullable=True),
                    sa.Column('iban', sa.String(), nullable=True),
                    sa.Column('swift', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('edrpou'),
                    sa.UniqueConstraint('iban'),
                    sa.UniqueConstraint('ipn'),
                    sa.UniqueConstraint('mfo'),
                    sa.UniqueConstraint('swift')
                    )
    op.create_index(op.f('ix_bank_list_name'), 'bank_list', ['name'], unique=True)
    op.create_table('currency',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('code', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_table('exchange_rates',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('bank_id', sa.Integer(), nullable=True),
                    sa.Column('currency_id', sa.Integer(), nullable=True),
                    sa.Column('purchase', sa.Float(), nullable=False),
                    sa.Column('sale', sa.Float(), nullable=False),
                    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['bank_id'], ['bank_list.id'], ),
                    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    op.drop_index(op.f('ix_bank_list_name'), table_name='bank_list')
    op.drop_table('bank_list')
    op.drop_index(op.f('ix_account_api_key'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
