"""Remove unique user

Revision ID: ac94fe999439
Revises: e273ab9d6b4e
Create Date: 2022-08-26 11:11:04.734531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac94fe999439'
down_revision = 'e273ab9d6b4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_name_key', 'account', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('account_name_key', 'account', ['name'])
    # ### end Alembic commands ###
