"""Unique exchange

Revision ID: e273ab9d6b4e
Revises: 27a6cad86571
Create Date: 2022-08-24 15:58:32.689589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e273ab9d6b4e'
down_revision = '27a6cad86571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_exchange_rates', 'exchange_rates', ['bank_id', 'currency_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_exchange_rates', 'exchange_rates', type_='unique')
    # ### end Alembic commands ###
